### ISSUE TITLE
main (and 1.0 tag) fails to build: missing AppDirectories.swift

### ISSUE THREAD

**Issue by daeh** [alexanderkoller/typstit#14]
I've been holding my breath hoping someone would make this. Thank you for putting in the work!

## Summary

Building from a fresh clone of `main` fails because `AppDirectories` is referenced in two files but never defined anywhere in the repo. It looks like the file was missed in commit a9d4d95 ("Typst binary consistently runs in the same workspace directory; closes #7"), which is also the commit tagged `1.0`.

## Build output

```
$ bash build-app.sh
==> Building release binary...
Building for production...
Sources/Typstit/Compiler/TypstCompiler.swift:40:26: error: cannot find 'AppDirectories' in scope
   40 |         let workspace  = AppDirectories.workspace
      |                          `- error: cannot find 'AppDirectories' in scope

Sources/Typstit/Compiler/TypstCompiler.swift:55:61: error: cannot infer contextual base in reference to member 'whitespacesAndNewlines'
   55 |             let msg = result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)
      |                                                             `- error: cannot infer contextual base in reference to member 'whitespacesAndNewlines'

Sources/Typstit/History/HistoryStore.swift:9:35: error: cannot find 'AppDirectories' in scope
    9 |     private var historyDir: URL { AppDirectories.appSupport.appendingPathComponent("history") }
      |                                   `- error: cannot find 'AppDirectories' in scope
```

(The `.whitespacesAndNewlines` error on line 55 is a cascade of the missing-symbol error — Swift's type inference fails downstream once `AppDirectories.workspace` can't be resolved.)

## Diagnosis

`git log --all -S AppDirectories` shows the symbol was introduced in a9d4d95, which refactored two pieces of existing path-handling code (`HistoryStore.appSupportURL` and `TypstCompiler.tempDir`) into a new `AppDirectories` namespace — but the file defining that namespace was never added to the commit. `git log --diff-filter=A` confirms no `AppDirectories.swift` has ever existed in the tree.

## Suggested fix (this worked for me)

Add `Sources/Typstit/AppDirectories.swift`:

```swift
import Foundation

enum AppDirectories {
    static let appSupport: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = base.appendingPathComponent("Typstit")
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()

    static let workspace: URL = {
        let dir = appSupport.appendingPathComponent("workspace")
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }()
}
```

This restores the behavior the prior code had (`appSupport` matches the old `HistoryStore.appSupportURL`) and gives `workspace` a stable on-disk location under Application Support rather than the previous per-launch UUID temp dir, which matches the intent described in #7.

With this file added, the build completes cleanly.

## Environment

- Commit: `8b9b97b` (current `main` tip); same failure on the `1.0` tag (a9d4d95)
- macOS 15.7.7 (24G720), Apple Silicon (arm64)
- Swift 6.2.4 / swift-driver 1.127.15, Xcode 26.3 (17C529)
- `Package.swift`: swift-tools-version 6.0, `platforms: [.macOS(.v13)]`, language mode v5
